//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.22 at 06:11:11 PM CET 
//


package model;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for generalResults element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="generalResults">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element name="lostMessages" type="{}percentage_t"/>
 *           &lt;element name="averageResponseTime" type="{}responseTime_t"/>
 *           &lt;element name="minResponseTime" type="{}responseTime_t"/>
 *           &lt;element name="maxResponseTime" type="{}responseTime_t"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lostMessages",
    "averageResponseTime",
    "minResponseTime",
    "maxResponseTime"
})

@XmlRootElement(name = "generalResults")
public class GeneralResults {

    @XmlElement(required = true)
    protected BigDecimal lostMessages;
    @XmlElement(required = true)
    protected ResponseTimeT averageResponseTime;
    @XmlElement(required = true)
    protected ResponseTimeT minResponseTime;
    @XmlElement(required = true)
    protected ResponseTimeT maxResponseTime;

    /**
     * Gets the value of the lostMessages property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLostMessages() {
        return lostMessages;
    }

    /**
     * Sets the value of the lostMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLostMessages(BigDecimal value) {
        this.lostMessages = value;
    }

    /**
     * Gets the value of the averageResponseTime property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseTimeT }
     *     
     */
    public ResponseTimeT getAverageResponseTime() {
        return averageResponseTime;
    }

    /**
     * Sets the value of the averageResponseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseTimeT }
     *     
     */
    public void setAverageResponseTime(ResponseTimeT value) {
        this.averageResponseTime = value;
    }

    /**
     * Gets the value of the minResponseTime property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseTimeT }
     *     
     */
    public ResponseTimeT getMinResponseTime() {
        return minResponseTime;
    }

    /**
     * Sets the value of the minResponseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseTimeT }
     *     
     */
    public void setMinResponseTime(ResponseTimeT value) {
        this.minResponseTime = value;
    }

    /**
     * Gets the value of the maxResponseTime property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseTimeT }
     *     
     */
    public ResponseTimeT getMaxResponseTime() {
        return maxResponseTime;
    }

    /**
     * Sets the value of the maxResponseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseTimeT }
     *     
     */
    public void setMaxResponseTime(ResponseTimeT value) {
        this.maxResponseTime = value;
    }
}
